-- NƏŞRLƏR (BOOKS) CƏDVƏLİ
CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  translator TEXT,
  isbn TEXT,
  price NUMERIC NOT NULL,
  discount_price NUMERIC,
  category_slugs TEXT[] NOT NULL,
  page_count INTEGER NOT NULL,
  publish_date TEXT NOT NULL,
  age_category TEXT NOT NULL,
  cover_type TEXT NOT NULL,
  dimensions TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  stars NUMERIC DEFAULT 5,
  review_count INTEGER DEFAULT 0,
  original_name TEXT,
  edition_count TEXT,
  edition_year_1 TEXT,
  edition_year_2 TEXT,
  edition_year_3 TEXT,
  edition_year_4 TEXT,
  cover_illustrator TEXT,
  illustrator TEXT,
  artist TEXT,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- MÖVCUD CƏDVƏLƏ YENİ SÜTUNLARIN ƏLAVƏ EDİLMƏSİ ÜÇÜN (Əgər cədvəl artıq varsa)
ALTER TABLE books ADD COLUMN IF NOT EXISTS original_name TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS edition_count TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS edition_year_1 TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS edition_year_2 TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS edition_year_3 TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS edition_year_4 TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_illustrator TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS illustrator TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS artist TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0;

-- KATEQORİYALAR CƏDVƏLİ
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  type TEXT DEFAULT 'kitab',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RƏYLƏR (REVIEWS) CƏDVƏLİ
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  admin_reply TEXT,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- SİYASƏTLƏR (POLICIES) - HƏR KƏSƏ OXUMA/YAZMA İCAZƏSİ
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON books FOR SELECT USING (true);
CREATE POLICY "Public profiles can insert." ON books FOR INSERT WITH CHECK (true);
CREATE POLICY "Public profiles can update." ON books FOR UPDATE USING (true);
CREATE POLICY "Public profiles can delete." ON books FOR DELETE USING (true);

CREATE POLICY "Public reviews are viewable by everyone." ON reviews FOR SELECT USING (true);
CREATE POLICY "Public reviews can insert." ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Public reviews can update." ON reviews FOR UPDATE USING (true);
CREATE POLICY "Public reviews can delete." ON reviews FOR DELETE USING (true);

CREATE POLICY "Public categories viewable by everyone." ON categories FOR SELECT USING (true);
CREATE POLICY "Public categories can insert." ON categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public categories can update." ON categories FOR UPDATE USING (true);
CREATE POLICY "Public categories can delete." ON categories FOR DELETE USING (true);

-- YENİ CƏDVƏLLƏR VƏ SİYASƏTLƏR --

-- SƏHİFƏLƏR (PAGES) CƏDVƏLİ
CREATE TABLE IF NOT EXISTS pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- BANNERLƏR CƏDVƏLİ
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position INTEGER NOT NULL,
  image TEXT NOT NULL,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- XƏBƏRLƏR CƏDVƏLİ
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- MENYULAR (NAV_ITEMS) CƏDVƏLİ
CREATE TABLE IF NOT EXISTS nav_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  href TEXT NOT NULL,
  position INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ALT MENYULAR (FOOTER_LINKS) CƏDVƏLİ
CREATE TABLE IF NOT EXISTS footer_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  href TEXT NOT NULL,
  position INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS AKTİVLƏŞDİRMƏ
ALTER TABLE pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE nav_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE footer_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- KÖHNƏ VƏ YA MÖVCUD SİYASƏTLƏRİ SİLMƏK (XƏTALARIN QARŞISINI ALMAQ ÜÇÜN)
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON books;
    DROP POLICY IF EXISTS "Public profiles can insert." ON books;
    DROP POLICY IF EXISTS "Public profiles can update." ON books;
    DROP POLICY IF EXISTS "Public profiles can delete." ON books;
    DROP POLICY IF EXISTS "Public reviews are viewable by everyone." ON reviews;
    DROP POLICY IF EXISTS "Public reviews can insert." ON reviews;
    DROP POLICY IF EXISTS "Public reviews can update." ON reviews;
    DROP POLICY IF EXISTS "Public reviews can delete." ON reviews;
    DROP POLICY IF EXISTS "Public categories viewable by everyone." ON categories;
    DROP POLICY IF EXISTS "Public categories can insert." ON categories;
    DROP POLICY IF EXISTS "Public categories can update." ON categories;
    DROP POLICY IF EXISTS "Public categories can delete." ON categories;
    DROP POLICY IF EXISTS "Public pages viewable by everyone." ON pages;
    DROP POLICY IF EXISTS "Public pages can insert." ON pages;
    DROP POLICY IF EXISTS "Public pages can update." ON pages;
    DROP POLICY IF EXISTS "Public pages can delete." ON pages;
    DROP POLICY IF EXISTS "Public banners viewable by everyone." ON banners;
    DROP POLICY IF EXISTS "Public banners can insert." ON banners;
    DROP POLICY IF EXISTS "Public banners can update." ON banners;
    DROP POLICY IF EXISTS "Public banners can delete." ON banners;
    DROP POLICY IF EXISTS "Public news viewable by everyone." ON news;
    DROP POLICY IF EXISTS "Public news can insert." ON news;
    DROP POLICY IF EXISTS "Public news can update." ON news;
    DROP POLICY IF EXISTS "Public news can delete." ON news;
    DROP POLICY IF EXISTS "Public nav_items viewable by everyone." ON nav_items;
    DROP POLICY IF EXISTS "Public nav_items can insert." ON nav_items;
    DROP POLICY IF EXISTS "Public nav_items can update." ON nav_items;
    DROP POLICY IF EXISTS "Public nav_items can delete." ON nav_items;
    DROP POLICY IF EXISTS "Public footer_links viewable by everyone." ON footer_links;
    DROP POLICY IF EXISTS "Public footer_links can insert." ON footer_links;
    DROP POLICY IF EXISTS "Public footer_links can update." ON footer_links;
    DROP POLICY IF EXISTS "Public footer_links can delete." ON footer_links;
END $$;

-- YENİ SİYASƏTLƏRİN (POLICIES) YARADILMASI (HƏR KƏSƏ OXUMA/YAZMA/SİLMƏ İCAZƏSİ)
CREATE POLICY "Public profiles are viewable by everyone." ON books FOR SELECT USING (true);
CREATE POLICY "Public profiles can insert." ON books FOR INSERT WITH CHECK (true);
CREATE POLICY "Public profiles can update." ON books FOR UPDATE USING (true);
CREATE POLICY "Public profiles can delete." ON books FOR DELETE USING (true);

CREATE POLICY "Public reviews are viewable by everyone." ON reviews FOR SELECT USING (true);
CREATE POLICY "Public reviews can insert." ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Public reviews can update." ON reviews FOR UPDATE USING (true);
CREATE POLICY "Public reviews can delete." ON reviews FOR DELETE USING (true);

CREATE POLICY "Public categories viewable by everyone." ON categories FOR SELECT USING (true);
CREATE POLICY "Public categories can insert." ON categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public categories can update." ON categories FOR UPDATE USING (true);
CREATE POLICY "Public categories can delete." ON categories FOR DELETE USING (true);

CREATE POLICY "Public pages viewable by everyone." ON pages FOR SELECT USING (true);
CREATE POLICY "Public pages can insert." ON pages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public pages can update." ON pages FOR UPDATE USING (true);
CREATE POLICY "Public pages can delete." ON pages FOR DELETE USING (true);

CREATE POLICY "Public banners viewable by everyone." ON banners FOR SELECT USING (true);
CREATE POLICY "Public banners can insert." ON banners FOR INSERT WITH CHECK (true);
CREATE POLICY "Public banners can update." ON banners FOR UPDATE USING (true);
CREATE POLICY "Public banners can delete." ON banners FOR DELETE USING (true);

CREATE POLICY "Public news viewable by everyone." ON news FOR SELECT USING (true);
CREATE POLICY "Public news can insert." ON news FOR INSERT WITH CHECK (true);
CREATE POLICY "Public news can update." ON news FOR UPDATE USING (true);
CREATE POLICY "Public news can delete." ON news FOR DELETE USING (true);

CREATE POLICY "Public nav_items viewable by everyone." ON nav_items FOR SELECT USING (true);
CREATE POLICY "Public nav_items can insert." ON nav_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public nav_items can update." ON nav_items FOR UPDATE USING (true);
CREATE POLICY "Public nav_items can delete." ON nav_items FOR DELETE USING (true);

CREATE POLICY "Public footer_links viewable by everyone." ON footer_links FOR SELECT USING (true);
CREATE POLICY "Public footer_links can insert." ON footer_links FOR INSERT WITH CHECK (true);
CREATE POLICY "Public footer_links can update." ON footer_links FOR UPDATE USING (true);
CREATE POLICY "Public footer_links can delete." ON footer_links FOR DELETE USING (true);
